import type { Product } from "@/src/types/catalog";

export const demoProducts: Product[] = [
  { id: "rice-001", slug: "premium-jasmine-rice", name: "Premium Jasmine Rice", description: "Fragrant, long-grain jasmine rice with a soft texture and delicate aroma for everyday family meals.", shortDescription: "Fragrant long-grain rice.", price: 18.99, category: "Rice & Grains", image: "/demo-products/premium-jasmine-rice.jpg", weight: "10 lb", isFeatured: true, isNew: false, isPopular: true },
  { id: "plantain-001", slug: "fresh-plantains", name: "Fresh Plantains", description: "A versatile kitchen staple, perfect for frying, baking, boiling, or serving alongside your favorite dishes.", shortDescription: "A versatile everyday staple.", price: 4.99, category: "Fresh Produce", image: "/demo-products/plantain.svg", weight: "Bundle", isFeatured: true, isNew: true, isPopular: true },
  { id: "oil-001", slug: "red-palm-oil", name: "Red Palm Oil", description: "Rich, aromatic red palm oil that adds depth and color to soups, stews, and traditional recipes.", shortDescription: "Rich and aromatic cooking oil.", price: 12.99, category: "Oils & Cooking", image: "/demo-products/oil.svg", weight: "1 L", isFeatured: true, isNew: false, isPopular: true },
  { id: "cassava-001", slug: "cassava-flour", name: "Cassava Flour", description: "Smooth, naturally gluten-free cassava flour for baking, thickening sauces, and classic African recipes.", shortDescription: "Smooth, naturally gluten-free flour.", price: 8.99, category: "African Foods", image: "/demo-products/flour.svg", weight: "2 lb", isFeatured: false, isNew: true, isPopular: false },
  { id: "yam-001", slug: "african-yam", name: "African Yam", description: "Firm, hearty yams selected for their satisfying texture in pounded yam, boiled dishes, and soups.", shortDescription: "Hearty, satisfying root vegetable.", price: 7.99, category: "Fresh Produce", image: "/demo-products/yam.svg", weight: "Each", isFeatured: false, isNew: false, isPopular: true },
  { id: "spice-001", slug: "suya-spice-blend", name: "Suya Spice Blend", description: "A warm, balanced blend of roasted peanuts and aromatic spices for grilled meats, vegetables, and more.", shortDescription: "Warm spices for grilling.", price: 6.99, category: "Spices & Seasoning", image: "/demo-products/spices.svg", weight: "250 g", isFeatured: true, isNew: false, isPopular: true },
  { id: "flour-001", slug: "golden-corn-flour", name: "Golden Corn Flour", description: "Fine golden corn flour for comforting porridge, baked goods, and traditional family favorites.", shortDescription: "Fine flour for everyday cooking.", price: 5.99, category: "African Foods", image: "/demo-products/flour.svg", weight: "2 lb", isFeatured: false, isNew: false, isPopular: false },
  { id: "noodles-001", slug: "instant-noodles", name: "Instant Noodles", description: "Quick, savory noodles for easy lunches, pantry meals, and creative bowls on busy days.", shortDescription: "A quick pantry favorite.", price: 4.49, category: "Snacks", image: "/demo-products/noodles.svg", weight: "Pack", isFeatured: false, isNew: true, isPopular: false },
  { id: "drink-001", slug: "hibiscus-drink", name: "Hibiscus Drink", description: "Bright, refreshing hibiscus drink with a gently tart finish, ready to enjoy chilled.", shortDescription: "Bright and refreshing.", price: 3.99, category: "Drinks", image: "/demo-products/drink.svg", weight: "Bottle", isFeatured: false, isNew: true, isPopular: true },
  { id: "chips-001", slug: "plantain-chips", name: "Plantain Chips", description: "Lightly salted, crisp plantain chips with a satisfying crunch for snacking anytime.", shortDescription: "Crisp, lightly salted crunch.", price: 3.49, category: "Snacks", image: "/demo-products/chips.svg", weight: "Bag", isFeatured: false, isNew: false, isPopular: true },
  { id: "beans-001", slug: "black-eyed-beans", name: "Black-Eyed Beans", description: "Creamy black-eyed beans that make a nourishing base for stews, salads, and comforting bowls.", shortDescription: "A nourishing pantry staple.", price: 6.49, category: "Rice & Grains", image: "/demo-products/beans.svg", weight: "2 lb", isFeatured: false, isNew: false, isPopular: false },
  { id: "ginger-001", slug: "ground-ginger", name: "Ground Ginger", description: "Fragrant ground ginger to bring gentle warmth and brightness to savory dishes and baking.", shortDescription: "Fragrant warmth for every dish.", price: 4.99, category: "Spices & Seasoning", image: "/demo-products/spices.svg", weight: "100 g", isFeatured: false, isNew: false, isPopular: false },
];

export function getDemoProduct(slug: string) {
  return demoProducts.find((product) => product.slug === slug);
}
